// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKSsge4abPqtQ_8bVoX6xMIqJNpcGikkw',
    appId: '1:887766899354:web:2379c68e1ed3a00d69dd23',
    messagingSenderId: '887766899354',
    projectId: 'expense-tracker-2baf6',
    authDomain: 'expense-tracker-2baf6.firebaseapp.com',
    storageBucket: 'expense-tracker-2baf6.appspot.com',
    measurementId: 'G-K0VD287N00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDqxV2RAATxQevsrA56sWbc-J0qA41tZI',
    appId: '1:887766899354:android:2119baa4066c473769dd23',
    messagingSenderId: '887766899354',
    projectId: 'expense-tracker-2baf6',
    storageBucket: 'expense-tracker-2baf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1cPGRKfC1G9k8p93G9nR3GF7zgyDThHE',
    appId: '1:887766899354:ios:94768454dce980e869dd23',
    messagingSenderId: '887766899354',
    projectId: 'expense-tracker-2baf6',
    storageBucket: 'expense-tracker-2baf6.appspot.com',
    iosBundleId: 'com.example.salmanExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1cPGRKfC1G9k8p93G9nR3GF7zgyDThHE',
    appId: '1:887766899354:ios:1df8145d59bebeeb69dd23',
    messagingSenderId: '887766899354',
    projectId: 'expense-tracker-2baf6',
    storageBucket: 'expense-tracker-2baf6.appspot.com',
    iosBundleId: 'com.example.salmanExpenseTracker.RunnerTests',
  );
}
